#!/bin/bash
#
# Publish messages to an SNS topic, specified by an ARN
#

if [ $# -ne 1 ]; then
    echo "usage: $0 <topic ARN>"
    exit 1
fi

case $1 in
    arn:aws:sns:*)  :   ;;
    *)  echo "ERROR: Topic ARN does not match 'arn:aws:sns:....'"
        exit 1
        ;;
esac

if [ -z "$AWS_DEFAULT_REGION" ]; then
    echo "You must set \$AWS_DEFAULT_REGION first"
    exit 1
fi

ARN=$1

echo "Publishing messages to the topic, counting up; Ctrl-C to stop"

COUNT=0
while true; do
    aws sns publish --topic-arn $ARN \
        --subject "Example message $COUNT" \
        --message "Message number $COUNT"
    COUNT=$(( $COUNT + 1 ))
    sleep 1
done
